const WineProducts = [
  {
    productId: 1,
    productName: "martini rose",
    image: "/images/PixCut-removebg_thumbnail 1 (1).svg",
    price: 6000,
    brand: "red wine",
    alcoholPerc: "12%",
        quantity: 75,
    ratings:4.5,
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos doloribus assumenda eum ab voluptatem aspernatur est totam iure a numquam fuga id ullam praesentium, tempore maiores officiis ducimus fugiat nostrum.",
  },

  {
    productId: 2,
    productName: "four cousins",
    image: "/images/PixCut-removebg_thumbnail 1.svg",
    price: 8000,
    brand: "red wine",
    alcoholPerc: "15%",
    quantity: 75,
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos doloribus assumenda eum ab voluptatem aspernatur est totam iure a numquam fuga id ullam praesentium, tempore maiores officiis ducimus fugiat nostrum.",
  },
  {
    productId: 3,
    productName: "declan red",
    image: "/images/PixCut-removebg_thumbnail 1 (1).svg",
    price: 8000,
    brand: "red wine",
    alcoholPerc: "12%",
    quantity: 75,
  },
  {
    productId: 4,
    productName: "carbenet sauvignon",
    image: "/images/PixCut-removebg_thumbnail 1 (1).svg",
    price: 10000,
    brand: "red wine",
    alcoholPerc: "17%",
    quantity: 75,
  },
  {
    productId: 5,
    productName: "merlot",
    image: "/images/PixCut-removebg_thumbnail 1 (1).svg",
    price: 5000,
    brand: "red wine",
    alcoholPerc: "7%",
    quantity: 75,
  },
  {
    productId: 6,
    productName: "zinfandel",
    image: "/images/PixCut-removebg_thumbnail 1 (1).svg",
    price: 6000,
    brand: "red wine",
    alcoholPerc: "5.5%",
    quantity: 75,
  },
  {
    productId: 7,
    productName: "nebbiolo",
    image: "/images/PixCut-removebg_thumbnail 1 (1).svg",
    price: 7000,
    brand: "red wine",
    alcoholPerc: "12%",
    quantity: 75,
  },
  {
    productId: 8,
    productName: "sangiovese",
    image: "/images/PixCut-removebg_thumbnail 1 (1).svg",
    price: 6000,
    brand: "red wine",
    alcoholPerc: "10%",
    quantity: 75,
  },
  {
    productId: 9,
    productName: "pinot noir",
    image: "/images/PixCut-removebg_thumbnail 1 (1).svg",
    price: 8000,
    brand: "red wine",
    alcoholPerc: "12%",
    quantity: 75,
  },
];
export default WineProducts