const WineProducts = [
  {
    productId: 1,
    productName: "martini rose",
    image: "/images/PixCut-removebg_thumbnail 1 (1).svg",
    price: 6000,
    brand: "red wine",
    alcoholPerc: "12%",
    quantity: 75,
    ratings: 4.5,
    isInCart: false,
  },

  {
    productId: 2,
    productName: "four cousins",
    image: "/images/PixCut-removebg (1) 1 (1).svg",
    price: 8000,
    brand: "red wine",
    alcoholPerc: "15%",
    quantity: 75,
    ratings: 4.5,
    isInCart: false,
  },
  {
    productId: 3,
    productName: "declan red",
    image: "/images/PixCut-removebg_thumbnail 1.svg",
    price: 8000,
    brand: "red wine",
    alcoholPerc: "12%",
    quantity: 75,
    ratings: 4.8,
    isInCart: false,
  },
  {
    productId: 4,
    productName: "carbenet sauvignon",
    image: "/images/image 17.svg",
    price: 10000,
    brand: "red wine",
    alcoholPerc: "17%",
    quantity: 75,
    ratings: 4.7,
    isInCart: false,
  },
  {
    productId: 5,
    productName: "merlot",
    image: "/images/image 18.svg",
    price: 5000,
    brand: "red wine",
    alcoholPerc: "7%",
    quantity: 75,
  },
  {
    productId: 6,
    productName: "zinfandel",
    image: "/images/image 19.svg",
    price: 6000,
    brand: "red wine",
    alcoholPerc: "5.5%",
    quantity: 75,
    ratings: 4.6,
  },
  {
    productId: 7,
    productName: "nebbiolo",
    image: "/images/image 20.svg",
    price: 7000,
    brand: "red wine",
    alcoholPerc: "12%",
    quantity: 75,
  },
  {
    productId: 8,
    productName: "sangiovese",
    image: "/images/image 21.svg",
    price: 6000,
    brand: "red wine",
    alcoholPerc: "10%",
    quantity: 75,
  },
  {
    productId: 9,
    productName: "pinot noir",
    image: "/images/image 22.svg",
    price: 8000,
    brand: "red wine",
    alcoholPerc: "12%",
    quantity: 75,
    ratings: 4.5,
  },
];
export default WineProducts